# Generated by Django 2.1.5 on 2020-02-15 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publishers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('AU', 'AUSTRALIA'), ('US', 'USA'), ('CA', 'CANADA')], default='AU', max_length=2)),
                ('category', models.CharField(blank=True, choices=[('BU', 'BUSINESS'), ('EN', 'ENTERTAINMENT'), ('HE', 'HEALTH'), ('SC', 'SCIENCE'), ('GN', 'GENERAL'), ('SP', 'SPORTS'), ('TE', 'TECHNOLOGY')], max_length=2, null=True)),
                ('author', models.CharField(blank=True, max_length=150, null=True)),
                ('title', models.CharField(max_length=400, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('url_to_image', models.URLField(blank=True, max_length=500, null=True, verbose_name='urlToImage')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='publishedAt')),
                ('content', models.TextField(blank=True, null=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_to_publisher', to='publishers.Publisher')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
